version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.70.0
        environment:
          SURREAL_URL: http://surreal:8000
          SURREAL_USER: root
          SURREAL_PASS: root
          SURREAL_NAMESPACE: myns
          SURREAL_DATABASE: mydb
      - image: surrealdb/surrealdb:latest
        name: surreal
        command: start --log trace --user root --pass root
    steps:
      - checkout
      - run: cargo test