version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.70.0
      - image: surrealdb/surrealdb:latest
        environment:
          SOME: thing
        command: start --log trace --user root --pass root
    steps:
      - checkout
      - run: cargo build